server:
  port: 41021


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.jozif.mcplm.entity

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  config: classpath:logback.xml

spring:
  profiles:
    active: 'h2'
#    active: 'dev'